### ISSUE TITLE
na_ontap_cluster issue with pre-cluster APIs

### ISSUE THREAD

**Issue by markrob** [ansible-collections/ansible_collections_netapp#14]
We have detected a couple of issues with the na_ontap_cluster module (added in 2.6).

Firstly, the apply() function makes API calls to get licenses and for autosupport_log.  However, those API calls fail if made prior to cluster setup i.e. before running the cluster-create API.

Secondly, the cluster-join API which is used to add additional nodes to an existing cluster is deprecated post ONTAP 9.2 and has been replaced with the cluster-node-add API.

We have written an updated module to use the new API and to only make the autosupport_log API call post cluster create.  We have also removed the license components as installing a base license is no longer a mandatory part of creating a cluster post ONTAP 9.2, and therefore can be handled using the na_ontap_license module.

**Comment by carchi8py** [comment]
This was pushed out as part of the 19.11.0 release.
